### ISSUE TITLE
Emergency clusterWriteLoop addProxiedSession panic error

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#556]
```
2020/10/14 21:55:15 cluster: stop msg received - multi sid usrF6DZPtYyirM-node-02
2020/10/14 21:55:15 cluster: session proxy closed usrF6DZPtYyirM-node-02
panic: runtime error: index out of range [0] with length 0

goroutine 229 [running]:
main.(*Topic).clusterWriteLoop(0xc0005d1d40)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1137 +0xa62
created by main.(*Topic).addProxiedSession
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3125 +0xb03
```

![image](https://user-images.githubusercontent.com/8274977/96000273-4e1fe480-0e69-11eb-8017-6ef3680b2d87.png)

![image](https://user-images.githubusercontent.com/8274977/96000393-6b54b300-0e69-11eb-9b93-949d7bdd1d00.png)

**Comment by or-else** [comment]
@aforge Could you please take a look.

**Comment by aforge** [comment]
Interesting. I have fixed a potential problem: https://github.com/tinode/chat/commit/3f5b019e57cfef6af0a6aa24705714d0aa665b35
Let me know if you observe any other problems.

**Comment by aforge** [comment]
@hhy5861 You may also want to patch this one: https://github.com/tinode/chat/commit/13441865b84e6cb865f20bf5b3400ff1a0280383

**Comment by hhy5861** [comment]
> @hhy5861 You may also want to patch this one: [1344186](https://github.com/tinode/chat/commit/13441865b84e6cb865f20bf5b3400ff1a0280383)

ok, thx

**Comment by hhy5861** [comment]
```
2020/10/21 02:59:49 cluster: stop msg received - multi sid grpWcnHgjfpNU0-node-08
2020/10/21 02:59:49 cluster: session proxy closed grpWcnHgjfpNU0-node-08
2020/10/21 02:59:49 cluster: session proxy closed grpWcnHgjfpNU0-node-15
2020/10/21 02:59:49 cluster: session proxy closed grpWcnHgjfpNU0-node-04
panic: runtime error: index out of range [2] with length 2

goroutine 617505 [running]:
main.(*Topic).clusterWriteLoop(0xc015624000)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1144 +0xb60
created by main.(*Topic).addProxiedSession
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3130 +0xb03
```

![image](https://user-images.githubusercontent.com/8274977/96632275-0fe36300-134a-11eb-8c6e-4b3ba150b83c.png)

@aforge @or-else 

- this problem still exists

**Comment by aforge** [comment]
@hhy5861 : my apologies for late response (I was traveling, just arrived at my destination).
Here's a temporary fix: https://github.com/tinode/chat/commit/67225b9166c43d75eeaa28ff48dae61cb22d16ba
I have identified the source of the problem. I'll make a proper fix tomorrow.

**Comment by hhy5861** [comment]
> @hhy5861 : my apologies for late response (I was traveling, just arrived at my destination).
> Here's a temporary fix: [67225b9](https://github.com/tinode/chat/commit/67225b9166c43d75eeaa28ff48dae61cb22d16ba)
> I have identified the source of the problem. I'll make a proper fix tomorrow.

Now there is a serious problem, `sub` did not return `ctrl`

**Comment by hhy5861** [comment]
> @hhy5861 : my apologies for late response (I was traveling, just arrived at my destination).
> Here's a temporary fix: [67225b9](https://github.com/tinode/chat/commit/67225b9166c43d75eeaa28ff48dae61cb22d16ba)
> I have identified the source of the problem. I'll make a proper fix tomorrow.

@aforge @or-else 
This problem is very serious, the response message will be lost, and a memory leak will also occur.

**Comment by or-else** [comment]
@aforge moved to Europe 2 days ago. His responses are delayed. He will get back to it as soon as he can.

**Comment by hhy5861** [comment]
```
File: spider-linux
Type: inuse_space
Time: Oct 24, 2020 at 2:35am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 10
Showing nodes accounting for 16221.35MB, 97.38% of 16657.33MB total
Dropped 292 nodes (cum <= 83.29MB)
Showing top 10 nodes out of 13
      flat  flat%   sum%        cum   cum%
15762.05MB 94.63% 94.63% 15782.56MB 94.75%  main.(*SessionStore).NewSession
  454.72MB  2.73% 97.36%   459.28MB  2.76%  main.newHub.func1
    4.58MB 0.027% 97.38% 14148.08MB 84.94%  main.(*Cluster).TopicMaster
         0     0% 97.38%    92.02MB  0.55%  main.(*Topic).run
         0     0% 97.38%  1702.31MB 10.22%  main.serveWebSocket
         0     0% 97.38%    94.08MB  0.56%  main.topicInit
         0     0% 97.38%  1702.31MB 10.22%  net/http.(*ServeMux).ServeHTTP
         0     0% 97.38%  1741.42MB 10.45%  net/http.(*conn).serve
         0     0% 97.38%  1702.31MB 10.22%  net/http.HandlerFunc.ServeHTTP
         0     0% 97.38%  1702.31MB 10.22%  net/http.serverHandler.ServeHTTP
```

**Comment by hhy5861** [comment]
···
goroutine profile: total 142928
124108 @ 0x437470 0x447833 0x44830a 0x4a4fe9 0xcc2708 0x467aa1
#	0x448309	reflect.rselect+0x389			/Users/mike/.gvm/gos/go1.14.9/src/runtime/select.go:544
#	0x4a4fe8	reflect.Select+0x178			/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:2236
#	0xcc2707	main.(*Topic).clusterWriteLoop+0x117	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1131

7753 @ 0x437470 0x447833 0xd1fdd8 0xd0149b 0x467aa1
#	0xd1fdd7	main.(*Topic).runProxy+0x257	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic_proxy.go:22
#	0xd0149a	main.(*Topic).run+0x3a		/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:212

2861 @ 0x437470 0x447833 0xd01c0d 0xd014b8 0x467aa1
#	0xd01c0c	main.(*Topic).runLocal+0x2bc	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:305
#	0xd014b7	main.(*Topic).run+0x57		/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:210

2568 @ 0x437470 0x43042a 0x42f995 0x4dec15 0x4dfaab 0x4dfa8d 0x645d2f 0x65874e 0x734640 0x47f711 0x73488c 0x732e45 0x736f6b 0x736f76 0x59aa73 0x59abdf 0xa65470 0xa679cc 0xa68a5f 0xa691df 0xccc222 0x467aa1
#	0x42f994	internal/poll.runtime_pollWait+0x54			/Users/mike/.gvm/gos/go1.14.9/src/runtime/netpoll.go:203
#	0x4dec14	internal/poll.(*pollDesc).wait+0x44			/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_poll_runtime.go:87
#	0x4dfaaa	internal/poll.(*pollDesc).waitRead+0x19a		/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_poll_runtime.go:92
#	0x4dfa8c	internal/poll.(*FD).Read+0x17c				/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_unix.go:169
#	0x645d2e	net.(*netFD).Read+0x4e					/Users/mike/.gvm/gos/go1.14.9/src/net/fd_unix.go:202
#	0x65874d	net.(*conn).Read+0x8d					/Users/mike/.gvm/gos/go1.14.9/src/net/net.go:184
#	0x73463f	crypto/tls.(*atLeastReader).Read+0x5f			/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:760
#	0x47f710	bytes.(*Buffer).ReadFrom+0xb0				/Users/mike/.gvm/gos/go1.14.9/src/bytes/buffer.go:204
#	0x73488b	crypto/tls.(*Conn).readFromUntil+0xeb			/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:782
#	0x732e44	crypto/tls.(*Conn).readRecordOrCCS+0x114		/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:589
#	0x736f6a	crypto/tls.(*Conn).readRecord+0x15a			/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:557
#	0x736f75	crypto/tls.(*Conn).Read+0x165				/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:1233
#	0x59aa72	bufio.(*Reader).fill+0x102				/Users/mike/.gvm/gos/go1.14.9/src/bufio/bufio.go:100
#	0x59abde	bufio.(*Reader).Peek+0x4e				/Users/mike/.gvm/gos/go1.14.9/src/bufio/bufio.go:138
#	0xa6546f	github.com/gorilla/websocket.(*Conn).read+0x3f		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370
#	0xa679cb	github.com/gorilla/websocket.(*Conn).advanceFrame+0x5b	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798
#	0xa68a5e	github.com/gorilla/websocket.(*Conn).NextReader+0x8e	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980
#	0xa691de	github.com/gorilla/websocket.(*Conn).ReadMessage+0x2e	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064
#	0xccc221	main.(*Session).readLoop+0x191				/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:53

2568 @ 0x437470 0x447833 0xccc598 0x467aa1
#	0xccc597	main.(*Session).writeLoop+0x1c7	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:76

1463 @ 0x437470 0x405f17 0x405bdb 0xd29f7e 0x467aa1
#	0xd29f7d	main.(*ClusterNode).callAsync.func1+0x3d	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:342

1171 @ 0x437470 0x44834f 0x448358 0x4a4fe9 0xcc2708 0x467aa1
#	0x448357	reflect.rselect+0x3d7			/Users/mike/.gvm/gos/go1.14.9/src/runtime/select.go:525
#	0x4a4fe8	reflect.Select+0x178			/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:2236
#	0xcc2707	main.(*Topic).clusterWriteLoop+0x117	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1131

126 @ 0x437470 0x4052fd 0x4050c5 0xd1ed04 0xd1f746 0xd037a9 0xd02aab 0xd014b8 0x467aa1
#	0xd1ed03	main.(*Topic).remProxiedSession+0x283	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3176
#	0xd1f745	main.(*Topic).remSession+0x3c5		/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3233
#	0xd037a8	main.(*Topic).handleLeaveRequest+0xd8	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:557
#	0xd02aaa	main.(*Topic).runLocal+0x115a		/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:338
#	0xd014b7	main.(*Topic).run+0x57			/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:210

59 @ 0x437470 0x448770 0x44875b 0x4483c2 0x4758f4 0xcf64fb 0xd2a656 0xccc2c1 0x467aa1
#	0x4483c1	sync.runtime_Semacquire+0x41		/Users/mike/.gvm/gos/go1.14.9/src/runtime/sema.go:56
#	0x4758f3	sync.(*WaitGroup).Wait+0x63		/Users/mike/.gvm/gos/go1.14.9/src/sync/waitgroup.go:130
#	0xcf64fa	main.(*Session).cleanUp+0x4a		/Users/mike/golang/poizon/duinfr/dewu-chat/server/session.go:369
#	0xd2a655	main.(*Session).readLoop.func1+0x35	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:41
#	0xccc2c0	main.(*Session).readLoop+0x230		/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:59

49 @ 0x437470 0x405f17 0x405c1b 0xcbca9f 0x467aa1
#	0xcbca9e	main.(*ClusterNode).asyncRpcLoop+0x6e	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:91

49 @ 0x437470 0x43042a 0x42f995 0x4dec15 0x4dfaab 0x4dfa8d 0x645d2f 0x65874e 0x59b12f 0x475db7 0x94a33f 0x94a2f2 0x954997 0x954eec 0x9551fb 0x95507d 0x9683a5 0x967675 0x467aa1
#	0x42f994	internal/poll.runtime_pollWait+0x54			/Users/mike/.gvm/gos/go1.14.9/src/runtime/netpoll.go:203
#	0x4dec14	internal/poll.(*pollDesc).wait+0x44			/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_poll_runtime.go:87
#	0x4dfaaa	internal/poll.(*pollDesc).waitRead+0x19a		/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_poll_runtime.go:92
#	0x4dfa8c	internal/poll.(*FD).Read+0x17c				/Users/mike/.gvm/gos/go1.14.9/src/internal/poll/fd_unix.go:169
#	0x645d2e	net.(*netFD).Read+0x4e					/Users/mike/.gvm/gos/go1.14.9/src/net/fd_unix.go:202
#	0x65874d	net.(*conn).Read+0x8d					/Users/mike/.gvm/gos/go1.14.9/src/net/net.go:184
#	0x59b12e	bufio.(*Reader).Read+0x24e				/Users/mike/.gvm/gos/go1.14.9/src/bufio/bufio.go:226
#	0x475db6	io.ReadAtLeast+0x86					/Users/mike/.gvm/gos/go1.14.9/src/io/io.go:310
#	0x94a33e	io.ReadFull+0x6e					/Users/mike/.gvm/gos/go1.14.9/src/io/io.go:329
#	0x94a2f1	encoding/gob.decodeUintReader+0x21			/Users/mike/.gvm/gos/go1.14.9/src/encoding/gob/decode.go:120
#	0x954996	encoding/gob.(*Decoder).recvMessage+0x56		/Users/mike/.gvm/gos/go1.14.9/src/encoding/gob/decoder.go:81
#	0x954eeb	encoding/gob.(*Decoder).decodeTypeSequence+0x10b	/Users/mike/.gvm/gos/go1.14.9/src/encoding/gob/decoder.go:143
#	0x9551fa	encoding/gob.(*Decoder).DecodeValue+0xda		/Users/mike/.gvm/gos/go1.14.9/src/encoding/gob/decoder.go:211
#	0x95507c	encoding/gob.(*Decoder).Decode+0x16c			/Users/mike/.gvm/gos/go1.14.9/src/encoding/gob/decoder.go:188
#	0x9683a4	net/rpc.(*gobClientCodec).ReadResponseHeader+0x44	/Users/mike/.gvm/gos/go1.14.9/src/net/rpc/client.go:228
#	0x967674	net/rpc.(*Client).input+0xa4				/Users/mike/.gvm/gos/go1.14.9/src/net/rpc/client.go:109
···

**Comment by hhy5861** [comment]
![image](https://user-images.githubusercontent.com/8274977/97082130-f2f4ab80-1639-11eb-9a3f-9f4e1a319e37.png)

**Comment by aforge** [comment]
@hhy5861 
I've sent https://github.com/tinode/chat/pull/559 for review. It should make the situation better.

**Comment by hhy5861** [comment]
> @hhy5861
> I've sent #559 for review. It should make the situation better.

![image](https://user-images.githubusercontent.com/8274977/97091730-9bbdfd80-1670-11eb-8bf3-d354b289ccd4.png)

 Updated your fix commit cpu full load

**Comment by aforge** [comment]
Can you grab a cpu profile please?

**Comment by hhy5861** [comment]
> @hhy5861
> 
> Can you grab a cpu profile please?

```
heap profile: 6010: 941128296 [4016301: 2211623256] @ heap/1048576
3639: 775077888 [3706: 789348352] @ 0xd019cf 0xcbf3f5 0x49cf4b 0x49c454 0x96b04f 0x467aa1
#	0xd019ce	main.(*SessionStore).NewSession+0x18e	/Users/mike/golang/poizon/duinfr/dewu-chat/server/sessionstore.go:72
#	0xcbf3f4	main.(*Cluster).TopicMaster+0xd64	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:462
#	0x49cf4a	reflect.Value.call+0x8aa		/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:460
#	0x49c453	reflect.Value.Call+0xb3			/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:321
#	0x96b04e	net/rpc.(*service).call+0x17e		/Users/mike/.gvm/gos/go1.14.9/src/net/rpc/server.go:377

770: 164003840 [2182: 464748544] @ 0xd019cf 0xcce0d2 0x7f89e4 0x7fa825 0x7fbd73 0x7f77dc 0x467aa1
#	0xd019ce	main.(*SessionStore).NewSession+0x18e	/Users/mike/golang/poizon/duinfr/dewu-chat/server/sessionstore.go:72
#	0xcce0d1	main.serveWebSocket+0x521		/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:170
#	0x7f89e3	net/http.HandlerFunc.ServeHTTP+0x43	/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2041
#	0x7fa824	net/http.(*ServeMux).ServeHTTP+0x1a4	/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2416
#	0x7fbd72	net/http.serverHandler.ServeHTTP+0xa2	/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2836
#	0x7f77db	net/http.(*conn).serve+0x86b		/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:1924

1: 524288 [1: 524288] @ 0xccf5b8 0xcdcfac 0x4370aa 0x467aa1
#	0xccf5b7	main.newHub+0x47	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:123
#	0xcdcfab	main.main+0x13cb	/Users/mike/golang/poizon/duinfr/dewu-chat/server/main.go:470
#	0x4370a9	runtime.main+0x1f9	/Users/mike/.gvm/gos/go1.14.9/src/runtime/proc.go:203

1: 458752 [1: 458752] @ 0x40df03 0x40dc9f 0x473b0e 0x472967 0xcd12f2 0xcd1296 0x467aa1
#	0x473b0d	sync.(*Map).dirtyLocked+0xad	/Users/mike/.gvm/gos/go1.14.9/src/sync/map.go:355
#	0x472966	sync.(*Map).Store+0x476		/Users/mike/.gvm/gos/go1.14.9/src/sync/map.go:157
#	0xcd12f1	main.(*Hub).topicPut+0x1401	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:112
#	0xcd1295	main.(*Hub).run+0x13a5		/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:208

25: 134400 [55: 295680] @ 0xa658c3 0xa6bba1 0xccdfb3 0x7f89e4 0x7fa825 0x7fbd73 0x7f77dc 0x467aa1
#	0xa658c2	github.com/gorilla/websocket.newConn+0x2c2		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:302
#	0xa6bba0	github.com/gorilla/websocket.(*Upgrader).Upgrade+0x530	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/server.go:202
#	0xccdfb2	main.serveWebSocket+0x402				/Users/mike/golang/poizon/duinfr/dewu-chat/server/hdl_websock.go:161
#	0x7f89e3	net/http.HandlerFunc.ServeHTTP+0x43			/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2041
#	0x7fa824	net/http.(*ServeMux).ServeHTTP+0x1a4			/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2416
#	0x7fbd72	net/http.serverHandler.ServeHTTP+0xa2			/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:2836
#	0x7f77db	net/http.(*conn).serve+0x86b				/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:1924

49: 100352 [64: 131072] @ 0xcd1091 0x467aa1
#	0xcd1090	main.(*Hub).run+0x11a0	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:190

20: 81920 [51: 208896] @ 0x731cff 0x7352e1 0x73567a 0x74e803 0x74ca3f 0x74c5f1 0x7376c1 0x7f710d 0x467aa1
#	0x731cfe	crypto/tls.(*halfConn).encrypt+0x11e				/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:447
#	0x7352e0	crypto/tls.(*Conn).writeRecordLocked+0x240			/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:940
#	0x735679	crypto/tls.(*Conn).writeRecord+0xb9				/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:966
#	0x74e802	crypto/tls.(*serverHandshakeState).doFullHandshake+0x282	/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/handshake_server.go:459
#	0x74ca3e	crypto/tls.(*serverHandshakeState).handshake+0x31e		/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/handshake_server.go:105
#	0x74c5f0	crypto/tls.(*Conn).serverHandshake+0x100			/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/handshake_server.go:60
#	0x7376c0	crypto/tls.(*Conn).Handshake+0x1e0				/Users/mike/.gvm/gos/go1.14.9/src/crypto/tls/conn.go:1342
#	0x7f710c	net/http.(*conn).serve+0x19c					/Users/mike/.gvm/gos/go1.14.9/src/net/http/server.go:1816

40: 81920 [63: 129024] @ 0xcd1045 0x467aa1
#	0xcd1044	main.(*Hub).run+0x1154	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:188

38: 77824 [61: 124928] @ 0xcd106b 0x467aa1
#	0xcd106a	main.(*Hub).run+0x117a	/Users/mike/golang/poizon/duinfr/dewu-chat/server/hub.go:189

1: 65536 [1: 65536] @ 0x87802c 0x877fa5 0x861629 0x8e2d65 0x8e2c3f 0x8e25ed 0x8e1b67 0x467aa1
#	0x87802b	google.golang.org/grpc/internal/transport.newBufWriter+0xeb		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http_util.go:542
#	0x877fa4	google.golang.org/grpc/internal/transport.newFramer+0x64		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http_util.go:595
#	0x861628	google.golang.org/grpc/internal/transport.newHTTP2Client+0xa88		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http2_client.go:259
#	0x8e2d64	google.golang.org/grpc/internal/transport.NewClientTransport+0x414	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/transport.go:577
#	0x8e2c3e	google.golang.org/grpc.(*addrConn).createTransport+0x2ee		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1282
#	0x8e25ec	google.golang.org/grpc.(*addrConn).tryAllAddrs+0x39c			/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1212
#	0x8e1b66	google.golang.org/grpc.(*addrConn).resetTransport+0x236			/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1127

224: 64512 [429302: 123638976] @ 0x447fda 0x4a4fe9 0xcc3297 0xcc3822 0x467aa1
#	0x447fd9	reflect.rselect+0x59				/Users/mike/.gvm/gos/go1.14.9/src/runtime/select.go:527
#	0x4a4fe8	reflect.Select+0x178				/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:2236
#	0xcc3296	main.(*Topic).clusterSelectProxyEvent+0xe6	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1127
#	0xcc3821	main.(*Topic).clusterWriteLoop+0x101		/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1170

19: 34048 [14758: 26446336] @ 0x447fda 0x4a4fe9 0xcc3297 0xcc3822 0x467aa1
#	0x447fd9	reflect.rselect+0x59				/Users/mike/.gvm/gos/go1.14.9/src/runtime/select.go:527
#	0x4a4fe8	reflect.Select+0x178				/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:2236
#	0xcc3296	main.(*Topic).clusterSelectProxyEvent+0xe6	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1127
#	0xcc3821	main.(*Topic).clusterWriteLoop+0x101		/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1170

1: 32768 [1: 32768] @ 0x878293 0x878356 0x861629 0x8e2d65 0x8e2c3f 0x8e25ed 0x8e1b67 0x467aa1
#	0x878292	bufio.NewReaderSize+0x352						/Users/mike/.gvm/gos/go1.14.9/src/bufio/bufio.go:56
#	0x878355	google.golang.org/grpc/internal/transport.newFramer+0x415		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http_util.go:593
#	0x861628	google.golang.org/grpc/internal/transport.newHTTP2Client+0xa88		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http2_client.go:259
#	0x8e2d64	google.golang.org/grpc/internal/transport.NewClientTransport+0x414	/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/transport.go:577
#	0x8e2c3e	google.golang.org/grpc.(*addrConn).createTransport+0x2ee		/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1282
#	0x8e25ec	google.golang.org/grpc.(*addrConn).tryAllAddrs+0x39c			/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1212
#	0x8e1b66	google.golang.org/grpc.(*addrConn).resetTransport+0x236			/Users/mike/.gvm/pkgsets/go1.14.9/global/pkg/mod/google.golang.org/grpc@v1.31.0/clientconn.go:1127

146: 32704 [333708: 74750592] @ 0x4a4ec4 0xcc3297 0xcc3822 0x467aa1
#	0x4a4ec3	reflect.Select+0x53				/Users/mike/.gvm/gos/go1.14.9/src/reflect/value.go:2170
#	0xcc3296	main.(*Topic).clusterSelectProxyEvent+0xe6	/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1127
#	0xcc3821	main.(*Topic).clusterWriteLoop+0x101		/Users/mike/golang/poizon/duinfr/dewu-chat/server/cluster.go:1170
```

![image](https://user-images.githubusercontent.com/8274977/97092268-636cee00-1675-11eb-85ad-4ef455a2343d.png)

**Comment by hhy5861** [comment]
> @hhy5861
> 
> Can you grab a cpu profile please?

```
Saved profile in /Users/mike/pprof/pprof.spider-linux.samples.cpu.007.pb.gz
File: spider-linux
Type: cpu
Time: Oct 25, 2020 at 4:00am (CST)
Duration: 30.17s, Total samples = 5mins (994.31%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 178.39s, 59.46% of 300.01s total
Dropped 734 nodes (cum <= 1.50s)
Showing top 10 nodes out of 96
      flat  flat%   sum%        cum   cum%
    30.24s 10.08% 10.08%     30.25s 10.08%  google.golang.org/grpc/internal/backoff.Exponential.Backoff
    28.95s  9.65% 19.73%     77.05s 25.68%  runtime.selectgo
    22.80s  7.60% 27.33%     79.44s 26.48%  runtime.mallocgc
    18.67s  6.22% 33.55%     22.40s  7.47%  runtime.heapBitsSetType
    18.01s  6.00% 39.56%     18.49s  6.16%  runtime.lock
    16.16s  5.39% 44.94%     16.24s  5.41%  runtime.unlock
    15.54s  5.18% 50.12%     21.13s  7.04%  runtime.scanobject
    12.65s  4.22% 54.34%    177.33s 59.11%  reflect.Select
     7.96s  2.65% 56.99%      7.96s  2.65%  runtime.nextFreeFast
     7.41s  2.47% 59.46%      7.41s  2.47%  runtime.memclrNoHeapPointers
(pprof) top 20
Showing nodes accounting for 3.64mins, 72.71% of 5mins total
Dropped 734 nodes (cum <= 0.03mins)
Showing top 20 nodes out of 96
      flat  flat%   sum%        cum   cum%
  0.50mins 10.08% 10.08%   0.50mins 10.08%  google.golang.org/grpc/internal/backoff.Exponential.Backoff
  0.48mins  9.65% 19.73%   1.28mins 25.68%  runtime.selectgo
  0.38mins  7.60% 27.33%   1.32mins 26.48%  runtime.mallocgc
  0.31mins  6.22% 33.55%   0.37mins  7.47%  runtime.heapBitsSetType
  0.30mins  6.00% 39.56%   0.31mins  6.16%  runtime.lock
  0.27mins  5.39% 44.94%   0.27mins  5.41%  runtime.unlock
  0.26mins  5.18% 50.12%   0.35mins  7.04%  runtime.scanobject
  0.21mins  4.22% 54.34%   2.96mins 59.11%  reflect.Select
  0.13mins  2.65% 56.99%   0.13mins  2.65%  runtime.nextFreeFast
  0.12mins  2.47% 59.46%   0.12mins  2.47%  runtime.memclrNoHeapPointers
  0.09mins  1.76% 61.22%   1.87mins 37.49%  reflect.rselect
  0.09mins  1.73% 62.95%   0.11mins  2.14%  runtime.findObject
  0.08mins  1.66% 64.61%   0.09mins  1.78%  runtime.nanotime
  0.08mins  1.60% 66.20%   0.08mins  1.60%  runtime.casgstatus
  0.06mins  1.28% 67.48%   0.06mins  1.28%  runtime.acquirem
  0.06mins  1.16% 68.64%   0.08mins  1.60%  runtime.releaseSudog
  0.05mins  1.08% 69.72%   0.08mins  1.54%  runtime.acquireSudog
  0.05mins  1.02% 70.74%   0.25mins  5.07%  runtime.chansend
  0.05mins  1.00% 71.74%   0.05mins  1.00%  runtime.(*hchan).sortkey
  0.05mins  0.97% 72.71%   0.24mins  4.85%  runtime.sellock
```

heap
```
File: spider-linux
Type: inuse_space
Time: Oct 25, 2020 at 4:02am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 10
Showing nodes accounting for 4770.88MB, 97.68% of 4883.97MB total
Dropped 203 nodes (cum <= 24.42MB)
Showing top 10 nodes out of 19
      flat  flat%   sum%        cum   cum%
 3854.36MB 78.92% 78.92%  3855.36MB 78.94%  main.(*SessionStore).NewSession
  390.15MB  7.99% 86.91%   390.15MB  7.99%  reflect.rselect
  361.59MB  7.40% 94.31%   751.74MB 15.39%  reflect.Select
  113.67MB  2.33% 96.64%   117.17MB  2.40%  main.(*Hub).run
      30MB  0.61% 97.25%   781.74MB 16.01%  main.(*Topic).clusterSelectProxyEvent
   20.60MB  0.42% 97.67%    26.61MB  0.54%  github.com/gorilla/websocket.newConn
    0.50MB  0.01% 97.68%  3333.88MB 68.26%  main.(*Cluster).TopicMaster
         0     0% 97.68%    26.61MB  0.54%  github.com/gorilla/websocket.(*Upgrader).Upgrade
         0     0% 97.68%   781.74MB 16.01%  main.(*Topic).clusterWriteLoop
         0     0% 97.68%    25.51MB  0.52%  main.(*Topic).run
```

**Comment by aforge** [comment]
@hhy5861 
If I am reading it correctly, it appears your chat server instances are consuming ~1 cpu each. The rest doesn't look that bad at a quick glance.
Are your instances being starved of cpu? What happens if you increase their cpu budget?

**Comment by hhy5861** [comment]
> @hhy5861
> If I am reading it correctly, it appears your chat server instances are consuming ~1 cpu each. The rest doesn't look that bad at a quick glance.
> Are your instances being starved of cpu? What happens if you increase their cpu budget?

@aforge 
Now there are 20 nodes, each node is 32 Core

**Comment by aforge** [comment]
@hhy5861 But is the single instance (node) maxing out all the 32 cores that are at its disposal?

**Comment by hhy5861** [comment]
> @hhy5861
> If I am reading it correctly, it appears your chat server instances are consuming ~1 cpu each. The rest doesn't look that bad at a quick glance.
> Are your instances being starved of cpu? What happens if you increase their cpu budget?



> @hhy5861 But is the single instance (node) maxing out all the 32 cores that are at its disposal?

Is it a bit wasteful to use a 1core cpu for each chat room? The monitoring chart above is fully loaded with 32core.

**Comment by aforge** [comment]
> Is it a bit wasteful to use a 1core cpu for each chat room? The monitoring chart above is fully loaded with 32core.

@hhy5861 Provisioning it totally up to you: you decide what's wasteful and what is not since only you know what your maximum load and traffic patterns are. Provisioning a single instance (node) so that it's running at ~80% of its maximum load may be a reasonable approach, i.e. if your sustained load is 1cpu, you provision it at 1.25cpu.

I have to go to bed now. If this problem is causing too much inconvenience to you, one simple (but undesirable) approach you can try is to nuke https://github.com/tinode/chat/commit/14384a156c56ca7d54218b853a1843546ce80541 in your repository - it'll roll the server back to using a shared goroutine pool for all topic events.

Also, I'd like to better understand your cluster load so I can reproduce it in a synthetic test:
* you have O(1000) sessions/topics per node. Correct?
* at what rate do incoming messages come and outgoing messages go in a sustained mode?
* if you were to bootstrap the cluster, at what rate do the clients arrive?

**Comment by hhy5861** [comment]
@or-else @aforge 
This modified version of the cpu has a big problem, I suggest you stress the sessions of 100,000 users

**Comment by aforge** [comment]
@hhy5861 
In order for me to be able to reproduce your usecase, I need some more information from you. Can you answer my questions about the params of your setup please?

**Comment by aforge** [comment]
@hhy5861 
Also, can you post the picture of your cpu profile displaying the full stacks of the functions where cpu samples were collected please? (e.g. by typing "svg" in the go profiler)

**Comment by hhy5861** [comment]
> @hhy5861
> Also, can you post the picture of your cpu profile displaying the full stacks of the functions where cpu samples were collected please? (e.g. by typing "svg" in the go profiler)

I have now rolled back the version. The impact on me is relatively large, I suggest that this can be reproduced through stress testing.
